- regExp: [".*\\.md+$", "docs"]
  labels: ["documentation"]
- regExp: "go\\.mod"
  labels: ["dependencies"]
- regExp: ".*\\.github"
  labels: ["workflow"]
- regExp: ".*\\.go+$"
  labels: ["code"]
- regExp: ".*_test\\.go+$"
  labels: ["unittests"]
- regExp: "LICENSE"
  labels: ["LICENSE", "danger-zone"]

- regExp: ["ttgapp"]
  labels: ["app engine"]
- regExp: ["main.go"]
  labels: ["main.go", "danger-zone"]
- regExp: ["ttgcore"]
  labels: ["game core"]
- regExp: ["ttgcore/ttgpcplayer"]
  labels: ["AI-logic"]
