- regExp: [".*\\.md+$", "docs"]
  labels: ["documentation"]
- regExp: "go\\.mod"
  labels: ["dependencies"]
- regExp: ".*\\.github"
  labels: ["workflow"]
- regExp: ".*\\.go+$"
  labels: ["code"]
- regExp: ".*_test\\.go+$"
  labels: ["unittests"]

- regExp: ["ttggame"]
  labels: ["game engine"]
- regExp: ["ttgmenu"]
  labels: ["menu engine"]
- regExp: ["main.go"]
  labels: ["main.go"]
