- regExp: [".*\\.md+$", "docs"]
  labels: ["documentation"]
- regExp: "go\\.mod"
  labels: ["dependencies"]
- regExp: ".*\\.github"
  labels: ["workflow"]
- regExp: ".*\\.go+$"
  labels: ["code"]
- regExp: ".*_test\\.go+$"
  labels: ["unittests"]
- regExp: "LICENSE"
  labels: ["LICENSE", "danger-zone"]

- regExp: ["ttggame"]
  labels: ["game engine"]
- regExp: ["ttgmenu"]
  labels: ["menu engine"]
- regExp: ["main.go", "danger-zone"]
  labels: ["main.go"]
- regExp: ["ttggame/ttgpcplayer"]
  labels: ["AI-logic"]
