version: "3"

services:
  app:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    security_opt:
      - label:type:container_runtime_t
    network_mode: bridge
