# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - run: sudo apt-get --allow-releaseinfo-change update
      - run: sudo apt-get install -y libgtk-3-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev libsdl2-dev libasound2-dev
      - run: sudo apt-get install -y xvfb
      - run: sudo apt-get install gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
      - run: make setup
      - run: make build
      - run: xvfb-run --auto-servernum go test -v -race ./...
      - run: golangci-lint run ./...
workflows:
  version: 2
  build:
    jobs:
      - build
