on: 
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "gucio321/tic-tac-go"
        source_branch: "master"
        destination_branch: "releases"
        github_token: ${{ secrets.GITHUB_TOKEN }}

