name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  Building:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/virtual-environments#available-environments
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout out source code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Set up Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
        id: go

      - name: Cache Go modules
        uses: actions/cache@v2.1.2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: make setup
        run: |
          make setup

      - name: make build
        run: |
          make build

      - name: make test
        run: |
          make test
